cloud = 0  # DONNT FORGET TO change this to 1 when uploading to streamlit!!

[passwords]
password = "shravan&amithrbest"

[easters]
easter_eggs = ['dob', 'mit', 'bcs', "rav"]
easter_eggs_counter = [10, 10, 10, 10]
temps = []
